name: Generar APK de Tiempo de HD
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Crear archivo APK
        run: |
          # Instalación de las herramientas necesarias
          npm install -g @pwabuilder/pwa-tooling
          
          # Generación del paquete. URL actualizada con tu página de GitHub
          pwabuilder package --platform android --url https://davidignacio9310.github.io/Tiempo-de-HD/ --output ./output
          
      - name: Subir el archivo APK generado
        uses: actions/upload-artifact@v4
        with:
          name: Tiempo-de-HD-APK
          path: ./output
